#!/usr/bin/env python3
"""Generate pemu_demos.py: pre-assembled demo setups for the MicroPython driver.

MicroPython on the demo board's RP2040 can't run the assembler (it needs
dataclasses and full regex support), so demos are assembled here into plain
lists of register writes.

    python3 sw/board/gen_demos.py > sw/board/pemu_demos.py
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from pemu.host import EngineConfig, config_writes, load_writes  # noqa: E402
from pemu.scenarios import (LED_PIN, SCL, SDA, UART_TX_PIN, i2c_cfg,  # noqa: E402
                            program)

CLK_HZ = 50_000_000
BAUD = 115_200
UART_DIV = round(CLK_HZ / (8 * BAUD)) - 1  # 53 -> 115,741 baud (+0.5%)


def setup(engine, prog, origin, cfg):
    return load_writes(prog, origin) + config_writes(engine, prog, origin, cfg)


def demos():
    tx, rx = program("uart_tx"), program("uart_rx")
    uart_tx_cfg = EngineConfig(clkdiv=UART_DIV, out_base=UART_TX_PIN, set_base=UART_TX_PIN,
                               set_count=1, out_right=True, x=7)
    yield "UART_LOOPBACK", (
        "Engine 0 transmits 8N1 on OUT12 (uo_out[4]); engine 1 receives it via "
        "internal loopback. Needs no external hardware.",
        setup(0, tx, 0, uart_tx_cfg)
        + setup(1, rx, len(tx), EngineConfig(clkdiv=UART_DIV, in_base=UART_TX_PIN,
                                             jmp_pin=UART_TX_PIN, in_right=True)),
        0x3, True, 1 << UART_TX_PIN)
    yield "UART_TX", (
        "8N1 at 115200 baud on OUT12 (uo_out[4]), the demo board's UART RX pin.",
        setup(0, tx, 0, uart_tx_cfg), 0x1, False, 1 << UART_TX_PIN)
    yield "WS2812", (
        "WS2812/NeoPixel data on OUT13 (uo_out[5]); push one GRB byte per word, in bits [15:8].",
        setup(0, program("ws2812"), 0, EngineConfig(clkdiv=round(CLK_HZ / 8e6) - 1,
                                                    side_base=LED_PIN, autopull=True,
                                                    pull_thresh=8)),
        0x1, False, 0)
    i2c = i2c_cfg()
    i2c.clkdiv = round(CLK_HZ / (10 * 100_000)) - 1  # ~100 kHz
    i2c.timeout = 2000
    yield "I2C", (
        f"I2C master at ~100 kHz, SDA on GPIO{SDA}, SCL on GPIO{SCL} (needs pull-ups).",
        setup(0, program("i2c_master"), 0, i2c), 0x1, False, 0)


def main():
    out = ['"""Pre-assembled PEMU demos. Generated by gen_demos.py - do not edit."""', ""]
    out.append(f"CLK_HZ = {CLK_HZ}")
    out.append("")
    out.append("# name: (description, register writes, engine enable mask, loopback, PIN_SET mask)")
    out.append("DEMOS = {")
    for name, (desc, writes, en, lb, pinset) in demos():
        out.append(f"    {name!r}: (")
        out.append(f"        {desc!r},")
        out.append("        (")
        for i in range(0, len(writes), 6):
            out.append("            " + " ".join(f"({a:#04x}, {v:#06x})," for a, v in writes[i:i + 6]))
        out.append("        ),")
        out.append(f"        {en:#x}, {lb}, {pinset:#06x}),")
    out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
