.program sd_cmd
; Sends 48-bit SD card commands over SPI mode 0, with the CRC7 generated by
; the CRC unit. The host pushes 5 words: the command byte and 4 argument
; bytes, each in bits [15:8]. The engine appends CRC7 and the end bit.
; Config: out_base = set_base = MOSI, side_base = SCK, set_count = 1,
; shift left, CRC_OUT, CRCPOLY = 0x1200 (x^7 + x^3 + 1, left-justified).
.side_set 1
.wrap_target
    mov crc, null       side 0
    set y, 4            side 0      ; 5 bytes
byte:
    pull                side 0
    set x, 7            side 0
bit:
    out pins, 1         side 0 [1]
    nop                 side 1 [1]  ; SCK high: card samples MOSI
    jmp x--, bit        side 0
    jmp y--, byte       side 0
    mov osr, crc        side 0      ; CRC7 is in bits [15:9]
    set x, 6            side 0
crc_bit:
    out pins, 1         side 0 [1]
    nop                 side 1 [1]
    jmp x--, crc_bit    side 0
    set pins, 1         side 0 [1]  ; end bit
    nop                 side 1 [1]
.wrap
